apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: mysql
type: Opaque
data:
  NAME: bXlkYXRhYmFzZQ== #mydatabase
  USER: QWxpbmE=
  PASSWORD: MTgxOA==
  HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo= #mysql-0.mysql.mysql.svc.cluster.local
