apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "MTgxOA==" # base64 "1818"
  MYSQL_USER: "QWxpbmE=" # base64 "Alina"
  MYSQL_PASSWORD: "MTgxOA==" # base64 "1818"
